# Generated by Django 4.0.6 on 2022-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Tags',
        ),
        migrations.AddField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
