# Generated by Django 4.0.6 on 2022-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_blog_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги'),
        ),
    ]
