# Generated by Django 4.0.6 on 2022-07-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact_graphic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Blog_info',
        ),
        migrations.DeleteModel(
            name='Graphic',
        ),
        migrations.AlterModelOptions(
            name='blog_info',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
    ]
