# Generated by Django 4.0.6 on 2022-08-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_contact_blog_info_delete_graphic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_info',
        ),
    ]
