# Generated by Django 4.0.6 on 2022-08-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_meta_description_article_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
