# Generated by Django 4.0.6 on 2022-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productcategory_product_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='is_mane',
            new_name='is_main',
        ),
    ]
